name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Use Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: Setup Tweego
        run: |
          TWEEDL_URL="https://github.com/tmedwards/tweego/releases/latest/download/tweego_linux64.zip"
          curl -L "$TWEEDL_URL" -o tweego.zip
          sudo mkdir -p /opt/tweego
          sudo unzip tweego.zip -d /opt/tweego
          sudo chmod +x /opt/tweego/tweego
          echo "/opt/tweego" >> $GITHUB_PATH
      - name: Build Site
        run: |
          tweego src/index.tw -o dist/index.html
          echo ":: StoryStylesheet [stylesheet]" > src/StoryStylesheet.tw
          sass src/.scss --no-source-map >> src/StoryStylesheet.tw
          tweego src -o index.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./
