name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Use Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: Setup Tweego
        run: |
          TWEEGO_VERSION="v2.1.1"
          FILE="tweego-2.1.1-linux-x64.zip"
          URL="https://github.com/tmedwards/tweego/releases/download/${TWEEGO_VERSION}/${FILE}"
          curl -L "$URL" -o "$FILE"
          ls -lh "$FILE"
          sudo mkdir -p /opt/tweego
          sudo unzip -o "$FILE" -d /opt/tweego
          sudo chmod +x /opt/tweego/tweego
          echo "/opt/tweego" >> $GITHUB_PATH
      - name: Build Site
        run: |
          echo ":: StoryStylesheet [stylesheet]" > src/StoryStylesheet.tw
          npx sass src/.scss --no-source-map >> src/StoryStylesheet.tw
          tweego src -o index.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./
